package evaluator

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/zyrakk/hivemind/internal/engine"
	"github.com/zyrakk/hivemind/internal/launcher"
	"github.com/zyrakk/hivemind/internal/llm"
	"github.com/zyrakk/hivemind/internal/recon"
	"github.com/zyrakk/hivemind/internal/state"
	"gopkg.in/yaml.v3"
)

type evaluatorLLM interface {
	Evaluate(ctx context.Context, task, diff, agentsMD string) (*llm.Evaluation, error)
}

type evaluatorLauncher interface {
	LaunchWorker(ctx context.Context, task launcher.Task, agentsMD string, cache string) (*launcher.Session, error)
	GetSession(sessionID string) (launcher.Session, bool)
	GetWorkDir() string
}

type evalEngine interface {
	Evaluate(ctx context.Context, req engine.EvalRequest) (*engine.EvalResult, error)
	ActiveEngine(ctx context.Context) string
}

type evalRecon interface {
	Run(ctx context.Context, commands []string) (*recon.Result, error)
}

type TaskChecklists struct {
	AutomatedChecklist []AutomatedCheck `json:"automated_checklist,omitempty"`
	UserChecklist      []UserCheck      `json:"user_checklist,omitempty"`
}

type AutomatedCheck struct {
	ID          string `json:"id"`
	Description string `json:"description"`
	Command     string `json:"command"`
	Type        string `json:"type"`
}

type UserCheck struct {
	ID          string `json:"id"`
	Description string `json:"description"`
}

type checkResult struct {
	Check  AutomatedCheck
	Passed bool
	Output string
}

type EvalResult struct {
	Verdict        string          `json:"verdict"`
	Evaluation     *llm.Evaluation `json:"evaluation"`
	Action         string          `json:"action"`
	RetryCount     int             `json:"retry_count"`
	NextSessionID  string          `json:"next_session_id,omitempty"`
	ConsultantUsed bool            `json:"consultant_used"`
}

type CompletionResult struct {
	Action        string `json:"action"`
	RetryCount    int    `json:"retry_count"`
	NextSessionID string `json:"next_session_id,omitempty"`
}

type notifier interface {
	NotifyNeedsInput(ctx context.Context, projectID, question, approvalID string) error
	NotifyPRReady(ctx context.Context, projectID, prURL, summary, approvalID string) error
}

type Evaluator struct {
	glm         evaluatorLLM
	consultants []llm.ConsultantClient
	launcher    evaluatorLauncher
	notifier    notifier
	engine      evalEngine
	recon       evalRecon
	db          *state.Store
	logger      *slog.Logger

	mu         sync.Mutex
	retries    map[int64]int
	checklists map[int64]TaskChecklists
}

func New(
	glm *llm.GLMClient,
	consultants []llm.ConsultantClient,
	launcher *launcher.Launcher,
	db *state.Store,
	logger *slog.Logger,
) *Evaluator {
	return NewWithDeps(glm, consultants, launcher, db, logger)
}

func NewWithDeps(
	glm evaluatorLLM,
	consultants []llm.ConsultantClient,
	launcher evaluatorLauncher,
	db *state.Store,
	logger *slog.Logger,
) *Evaluator {
	if logger == nil {
		logger = slog.New(slog.NewTextHandler(io.Discard, nil))
	}

	return &Evaluator{
		glm:         glm,
		consultants: consultants,
		launcher:    launcher,
		db:          db,
		logger:      logger,
		retries:    make(map[int64]int),
		checklists: make(map[int64]TaskChecklists),
	}
}

func (e *Evaluator) SetNotifier(n notifier) {
	if e == nil {
		return
	}

	e.mu.Lock()
	defer e.mu.Unlock()
	e.notifier = n
}

func (e *Evaluator) SetEngine(engine evalEngine) {
	if e == nil {
		return
	}

	e.mu.Lock()
	defer e.mu.Unlock()
	e.engine = engine
}

func (e *Evaluator) SetRecon(recon evalRecon) {
	if e == nil {
		return
	}

	e.mu.Lock()
	defer e.mu.Unlock()
	e.recon = recon
}

func (e *Evaluator) SetTaskChecklists(taskID int64, checklists TaskChecklists) {
	e.mu.Lock()
	defer e.mu.Unlock()
	if e.checklists == nil {
		e.checklists = make(map[int64]TaskChecklists)
	}
	e.checklists[taskID] = checklists
}

func (e *Evaluator) getTaskChecklists(taskID int64) (TaskChecklists, bool) {
	e.mu.Lock()
	defer e.mu.Unlock()
	cl, ok := e.checklists[taskID]
	return cl, ok
}

func (e *Evaluator) hasAnyChecklists() bool {
	e.mu.Lock()
	defer e.mu.Unlock()
	return len(e.checklists) > 0
}

// allowedChecklistPrefixes defines safe command prefixes for automated checklist commands.
// Commands generated by the LLM must start with one of these prefixes.
var allowedChecklistPrefixes = []string{
	"go build", "go test", "go vet",
	"test -f", "test -d", "test -e",
	"grep -q", "grep -c", "grep -l",
	"cat ", "head ", "tail ", "wc ",
	"ls ", "stat ",
}

func isAllowedChecklistCommand(cmd string) bool {
	cmd = strings.TrimSpace(cmd)
	for _, prefix := range allowedChecklistPrefixes {
		if strings.HasPrefix(cmd, prefix) {
			return true
		}
	}
	return false
}

func (e *Evaluator) evaluateWithChecklist(ctx context.Context, checklists TaskChecklists, repoPath string) ([]checkResult, error) {
	if e.recon == nil {
		return nil, fmt.Errorf("recon not configured for checklist evaluation")
	}

	results := make([]checkResult, 0, len(checklists.AutomatedChecklist))
	for _, check := range checklists.AutomatedChecklist {
		cmd := strings.TrimSpace(check.Command)
		if cmd == "" {
			continue
		}
		if !isAllowedChecklistCommand(cmd) {
			e.logger.Warn("checklist command rejected by allowlist",
				slog.String("command", cmd), slog.String("check_id", check.ID))
			results = append(results, checkResult{
				Check:  check,
				Passed: false,
				Output: fmt.Sprintf("command rejected: not in allowlist (must start with one of: %s)", strings.Join(allowedChecklistPrefixes, ", ")),
			})
			continue
		}
		if repoPath != "" {
			cmd = fmt.Sprintf("cd %s && %s", shellQuotePath(repoPath), cmd)
		}
		runResult, runErr := e.recon.Run(ctx, []string{cmd})
		passed := runErr == nil && runResult != nil && len(runResult.Errors) == 0
		output := ""
		if runResult != nil {
			output = runResult.Output
		}
		if runErr != nil && output == "" {
			output = runErr.Error()
		}
		results = append(results, checkResult{
			Check:  check,
			Passed: passed,
			Output: output,
		})
	}
	return results, nil
}

func (e *Evaluator) Evaluate(ctx context.Context, diff, criteria string) (*llm.Evaluation, error) {
	if e == nil || e.glm == nil {
		return nil, llm.ErrNotImplemented
	}

	return e.glm.Evaluate(ctx, criteria, diff, "")
}

func (e *Evaluator) EvaluateWorkerOutput(ctx context.Context, session launcher.Session) (*EvalResult, error) {
	if e == nil {
		return nil, fmt.Errorf("evaluator is nil")
	}
	e.mu.Lock()
	evalNotifier := e.notifier
	eng := e.engine
	rc := e.recon
	e.mu.Unlock()
	if eng == nil && e.glm == nil && !e.hasAnyChecklists() {
		return nil, fmt.Errorf("glm client is not configured")
	}

	taskRecord, projectName, err := e.findTaskForSession(ctx, session)
	if err != nil {
		return nil, err
	}

	agentsMD, err := readProjectAgentsForEvaluation(session.ProjectID, projectName)
	if err != nil {
		return nil, err
	}

	var evaluation *llm.Evaluation
	var diff string

	// Checklist-based evaluation: runs before engine/GLM to save quota
	checklists, taskHasChecklists := e.getTaskChecklists(taskRecord.ID)
	if taskHasChecklists && len(checklists.AutomatedChecklist) > 0 && rc != nil {
		repoPath := resolveRepoPathForEval(projectName, session, launcherWorkDir(e.launcher))
		checkResults, checkErr := e.evaluateWithChecklist(ctx, checklists, repoPath)
		if checkErr == nil {
			allPassed := true
			var failedChecks []string
			for _, cr := range checkResults {
				if !cr.Passed {
					allPassed = false
					failedChecks = append(failedChecks, fmt.Sprintf("[%s] %s: %s", cr.Check.ID, cr.Check.Description, cr.Output))
				}
			}

			if allPassed && len(checklists.UserChecklist) == 0 {
				evaluation = &llm.Evaluation{
					Verdict:      "accept",
					Confidence:   0.9,
					Completeness: 0.9,
					Correctness:  0.9,
					Conventions:  0.9,
					ScopeOK:      true,
					Summary:      fmt.Sprintf("All %d automated checks passed", len(checkResults)),
				}
				goto postEval
			}

			if allPassed && len(checklists.UserChecklist) > 0 {
				if evalNotifier != nil {
					var userCheckLines []string
					for _, uc := range checklists.UserChecklist {
						userCheckLines = append(userCheckLines, fmt.Sprintf("- %s", uc.Description))
					}
					projectRef := strings.TrimSpace(projectName)
					if projectRef == "" {
						projectRef = strconv.FormatInt(taskRecord.ProjectID, 10)
					}
					question := fmt.Sprintf("Task '%s' passed automated checks. Please verify:\n%s",
						strings.TrimSpace(taskRecord.Title),
						strings.Join(userCheckLines, "\n"))
					approvalID := fmt.Sprintf("input-%d-%d", taskRecord.ProjectID, taskRecord.ID)
					_ = evalNotifier.NotifyNeedsInput(ctx, projectRef, question, approvalID)
				}
				evaluation = &llm.Evaluation{
					Verdict:      "accept",
					Confidence:   0.8,
					Completeness: 0.9,
					Correctness:  0.9,
					Conventions:  0.9,
					ScopeOK:      true,
					Summary:      fmt.Sprintf("All %d automated checks passed. User checklist sent for review.", len(checkResults)),
				}
				goto postEval
			}

			// Some automated checks failed
			evaluation = &llm.Evaluation{
				Verdict:      "iterate",
				Confidence:   0.8,
				Completeness: 0.5,
				Correctness:  0.4,
				Conventions:  0.9,
				ScopeOK:      false,
				Summary:      fmt.Sprintf("%d/%d automated checks failed", len(failedChecks), len(checkResults)),
			}
			for _, fc := range failedChecks {
				evaluation.Issues = append(evaluation.Issues, llm.Issue{
					Severity:    "high",
					Description: fc,
					Suggestion:  "Fix the failing check",
				})
			}
			goto postEval
		}
		// If checklist eval errored, fall through to engine/GLM evaluation
		e.logger.Warn("checklist evaluation failed, falling back to engine eval",
			slog.String("error", checkErr.Error()))
	}

	// If checklist didn't handle this task, ensure we have an evaluation backend
	if eng == nil && e.glm == nil {
		return nil, fmt.Errorf("no evaluation backend available for task %d", taskRecord.ID)
	}

	diff = strings.TrimSpace(session.Diff)
	if diff == "" {
		diff, err = e.collectDiff(session.Branch)
		if err != nil {
			return nil, err
		}
	}
	if eng != nil {
		var buildOut, testOut, vetOut string
		if rc != nil {
			repoPath := resolveRepoPathForEval(projectName, session, launcherWorkDir(e.launcher))
			if repoPath != "" {
				buildResult, _ := rc.Run(ctx, []string{fmt.Sprintf("cd %s && go build ./... 2>&1", shellQuotePath(repoPath))})
				if buildResult != nil {
					buildOut = buildResult.Output
				}
				testResult, _ := rc.Run(ctx, []string{fmt.Sprintf("cd %s && go test ./... 2>&1 | head -100", shellQuotePath(repoPath))})
				if testResult != nil {
					testOut = testResult.Output
				}
				vetResult, _ := rc.Run(ctx, []string{fmt.Sprintf("cd %s && go vet ./... 2>&1", shellQuotePath(repoPath))})
				if vetResult != nil {
					vetOut = vetResult.Output
				}
			}
		}

		engineResult, engineErr := eng.Evaluate(ctx, engine.EvalRequest{
			TaskID:      strconv.FormatInt(taskRecord.ID, 10),
			TaskTitle:   taskRecord.Title,
			TaskDesc:    taskRecord.Description,
			DiffContent: diff,
			BuildOutput: buildOut,
			TestOutput:  testOut,
			VetOutput:   vetOut,
			AgentsMD:    agentsMD,
		})
		if engineErr == nil {
			evaluation = convertEngineEvalToLLMEval(engineResult)
			goto postEval
		}

		e.logger.Warn("engine evaluate failed, falling back to GLM",
			slog.String("error", engineErr.Error()))
		if e.glm == nil {
			return nil, fmt.Errorf("engine evaluation failed: %w", engineErr)
		}
	}

	evaluation, err = e.glm.Evaluate(ctx, taskRecord.Description, diff, agentsMD)
	if err != nil {
		return nil, fmt.Errorf("glm evaluation failed: %w", err)
	}

postEval:
	consultantUsed := false
	forceIterate := false
	if evaluation.Confidence < 0.5 {
		consultant := firstAvailableConsultant(e.consultants)
		if consultant != nil {
			consultantUsed = true
			evalJSON, _ := json.Marshal(evaluation)
			opinion, consultErr := consultant.Consult(
				ctx,
				"output_evaluation",
				agentsMD,
				fmt.Sprintf("Valida esta evaluacion: %s\n\nDiff:\n%s", string(evalJSON), diff),
			)
			if consultErr != nil {
				e.logger.Warn("consultant evaluation failed", slog.Any("error", consultErr), slog.String("consultant", consultant.GetName()))
			} else if opinion != nil && !opinion.AgreeWithOriginal {
				forceIterate = true
			}
		}
	}

	taskID := taskRecord.ID
	retryCount := e.getRetryCount(taskID)
	action := decideAction(evaluation, forceIterate, retryCount)
	nextSessionID := ""
	workerRef := optionalWorkerID(session.WorkerID)

	switch action {
	case "accept":
		status := state.TaskStatusCompleted
		if e.db != nil && taskID > 0 {
			if updateErr := e.db.UpdateTask(ctx, taskID, state.TaskUpdate{Status: &status}); updateErr != nil {
				return nil, fmt.Errorf("mark task %d completed: %w", taskID, updateErr)
			}
		}
		if evalNotifier != nil {
			projectRef := strings.TrimSpace(projectName)
			if projectRef == "" {
				projectRef = strconv.FormatInt(taskRecord.ProjectID, 10)
			}
			summary := strings.TrimSpace(evaluation.Summary)
			if summary == "" {
				summary = fmt.Sprintf("Task '%s' accepted and ready for review", strings.TrimSpace(taskRecord.Title))
			}
			approvalID := fmt.Sprintf("pr-%d-%d", taskRecord.ProjectID, taskID)
			_ = evalNotifier.NotifyPRReady(ctx, projectRef, "", summary, approvalID)
		}
	case "iterate":
		nextRetry := retryCount + 1
		e.setRetryCount(taskID, nextRetry)

		cache := buildIterationCache(session, evaluation, nextRetry)
		newSession, launchErr := e.launcher.LaunchWorker(ctx, launcher.Task{
			ProjectID:     session.ProjectID,
			ID:            strconv.FormatInt(taskID, 10),
			Title:         taskRecord.Title,
			Description:   taskRecord.Description,
			BranchName:    retryBranchName(session.Branch, nextRetry),
			FilesAffected: nil,
		}, agentsMD, cache)
		if launchErr != nil {
			action = "escalate"
			if escalateErr := e.escalateToUser(ctx, taskRecord.ProjectID, taskID, workerRef, "failed to launch retry worker: "+launchErr.Error()); escalateErr != nil {
				return nil, escalateErr
			}
			break
		}
		nextSessionID = newSession.SessionID

		status := state.TaskStatusInProgress
		update := state.TaskUpdate{Status: &status}
		if newSession.WorkerID > 0 {
			workerID := newSession.WorkerID
			update.AssignedWorkerIDSet = true
			update.AssignedWorkerID = &workerID
		}
		if e.db != nil && taskID > 0 {
			if updateErr := e.db.UpdateTask(ctx, taskID, update); updateErr != nil {
				if update.AssignedWorkerIDSet {
					statusOnly := state.TaskUpdate{Status: &status}
					if retryErr := e.db.UpdateTask(ctx, taskID, statusOnly); retryErr == nil {
						retryCount = nextRetry
						break
					}
				}
				return nil, fmt.Errorf("mark task %d in progress for retry: %w", taskID, updateErr)
			}
		}
		retryCount = nextRetry
	case "escalate":
		if escalateErr := e.escalateToUser(ctx, taskRecord.ProjectID, taskID, workerRef, escalationReason(evaluation)); escalateErr != nil {
			return nil, escalateErr
		}
	}

	return &EvalResult{
		Verdict:        evaluation.Verdict,
		Evaluation:     evaluation,
		Action:         action,
		RetryCount:     retryCount,
		NextSessionID:  nextSessionID,
		ConsultantUsed: consultantUsed,
	}, nil
}

func (e *Evaluator) HandleWorkerCompletion(ctx context.Context, sessionID string) error {
	_, err := e.HandleWorkerCompletionDetailed(ctx, sessionID)
	return err
}

func (e *Evaluator) HandleWorkerCompletionDetailed(ctx context.Context, sessionID string) (*CompletionResult, error) {
	if e == nil {
		return nil, fmt.Errorf("evaluator is nil")
	}
	if e.launcher == nil {
		reason := "evaluator launcher is not configured"
		e.logger.Warn("evaluation skipped: "+reason, slog.String("session_id", sessionID))
		return nil, fmt.Errorf(reason)
	}

	e.logger.Info(
		fmt.Sprintf("evaluating worker output for session %s", sessionID),
		slog.String("session_id", sessionID),
	)

	session, ok := e.launcher.GetSession(sessionID)
	if !ok {
		reason := fmt.Sprintf("session %s not found", sessionID)
		e.logger.Warn("evaluation skipped: "+reason, slog.String("session_id", sessionID))
		return nil, fmt.Errorf(reason)
	}

	if session.Status == state.WorkerStatusCompleted {
		evalResult, err := e.EvaluateWorkerOutput(ctx, session)
		if err != nil {
			e.logger.Warn("evaluation skipped: "+err.Error(), slog.String("session_id", sessionID))
			return nil, err
		}
		if evalResult == nil {
			reason := "evaluate worker output returned nil result"
			e.logger.Warn("evaluation skipped: "+reason, slog.String("session_id", sessionID))
			return &CompletionResult{Action: "escalate"}, nil
		}
		return &CompletionResult{
			Action:        evalResult.Action,
			RetryCount:    evalResult.RetryCount,
			NextSessionID: evalResult.NextSessionID,
		}, nil
	}

	taskRecord, projectName, err := e.findTaskForSession(ctx, session)
	if err != nil {
		return nil, err
	}

	retryCount := e.getRetryCount(taskRecord.ID)
	if retryCount >= 2 {
		if escalateErr := e.escalateToUser(ctx, taskRecord.ProjectID, taskRecord.ID, optionalWorkerID(session.WorkerID), "worker failed and retry limit was reached"); escalateErr != nil {
			return nil, escalateErr
		}
		return &CompletionResult{
			Action:     "escalate",
			RetryCount: retryCount,
		}, nil
	}

	agentsMD, err := readProjectAgentsForEvaluation(session.ProjectID, projectName)
	if err != nil {
		return nil, err
	}

	nextRetry := retryCount + 1
	e.setRetryCount(taskRecord.ID, nextRetry)

	cache := fmt.Sprintf("Worker previo fallo. Error: %s\nReintento #%d", strings.TrimSpace(session.Error), nextRetry)
	newSession, launchErr := e.launcher.LaunchWorker(ctx, launcher.Task{
		ProjectID:   session.ProjectID,
		ID:          strconv.FormatInt(taskRecord.ID, 10),
		Title:       taskRecord.Title,
		Description: taskRecord.Description,
		BranchName:  retryBranchName(session.Branch, nextRetry),
	}, agentsMD, cache)
	if launchErr != nil {
		if escalateErr := e.escalateToUser(ctx, taskRecord.ProjectID, taskRecord.ID, optionalWorkerID(session.WorkerID), "failed to relaunch worker: "+launchErr.Error()); escalateErr != nil {
			return nil, escalateErr
		}
		return &CompletionResult{
			Action:     "escalate",
			RetryCount: nextRetry,
		}, nil
	}

	status := state.TaskStatusInProgress
	update := state.TaskUpdate{Status: &status}
	if newSession.WorkerID > 0 {
		workerID := newSession.WorkerID
		update.AssignedWorkerIDSet = true
		update.AssignedWorkerID = &workerID
	}
	if e.db != nil {
		_ = e.db.UpdateTask(ctx, taskRecord.ID, update)
	}

	return &CompletionResult{
		Action:        "iterate",
		RetryCount:    nextRetry,
		NextSessionID: newSession.SessionID,
	}, nil
}

func (e *Evaluator) findTaskForSession(ctx context.Context, session launcher.Session) (state.Task, string, error) {
	if e.db == nil {
		return state.Task{}, "", fmt.Errorf("state store is not configured")
	}

	searchProjects := make([]state.ProjectSummary, 0)
	if session.ProjectID > 0 {
		project, err := e.db.GetProjectByID(ctx, session.ProjectID)
		if err == nil {
			searchProjects = append(searchProjects, state.ProjectSummary{InternalID: project.ID, Name: project.Name})
		}
	}
	if len(searchProjects) == 0 {
		summaries, err := e.db.ListProjectSummaries(ctx)
		if err != nil {
			return state.Task{}, "", err
		}
		searchProjects = append(searchProjects, summaries...)
	}

	for _, summary := range searchProjects {
		detail, err := e.db.GetProjectDetail(ctx, strconv.FormatInt(summary.InternalID, 10))
		if err != nil {
			continue
		}

		for _, task := range detail.Tasks {
			if task.AssignedWorkerID != nil && session.WorkerID > 0 && *task.AssignedWorkerID == session.WorkerID {
				if session.ProjectID == 0 {
					session.ProjectID = summary.InternalID
				}
				return task, detail.Project.Name, nil
			}
		}
	}

	return state.Task{}, "", fmt.Errorf("task not found for session %s", session.SessionID)
}

func (e *Evaluator) collectDiff(branch string) (string, error) {
	if strings.TrimSpace(branch) == "" {
		return "", fmt.Errorf("branch is required to collect diff")
	}

	workDir := "."
	if e.launcher != nil && strings.TrimSpace(e.launcher.GetWorkDir()) != "" {
		workDir = e.launcher.GetWorkDir()
	}

	output, err := runGitDiff(workDir, "main..."+branch)
	if err != nil {
		fallback, fallbackErr := runGitDiff(workDir, "")
		if fallbackErr != nil {
			return "", fmt.Errorf("collect diff for branch %s: %w", branch, err)
		}
		return fallback, nil
	}

	return output, nil
}

func runGitDiff(workDir, revision string) (string, error) {
	args := []string{"-C", workDir, "diff"}
	if strings.TrimSpace(revision) != "" {
		args = append(args, revision)
	}

	cmd := exec.Command("git", args...)
	var buf bytes.Buffer
	cmd.Stdout = &buf
	cmd.Stderr = &buf
	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("git diff %s: %w (%s)", revision, err, strings.TrimSpace(buf.String()))
	}

	return strings.TrimSpace(buf.String()), nil
}

func readProjectAgentsForEvaluation(projectID int64, projectName string) (string, error) {
	candidates := make([]string, 0, 8)
	if strings.TrimSpace(projectName) != "" {
		name := strings.TrimSpace(projectName)
		lower := strings.ToLower(name)
		candidates = append(candidates,
			filepath.Join("agents", name+".md"),
			filepath.Join("agents", lower+".md"),
			filepath.Join("/app/agents", name+".md"),
			filepath.Join("/app/agents", lower+".md"),
		)
	}
	if projectID > 0 {
		numStr := fmt.Sprintf("%d.md", projectID)
		candidates = append(candidates,
			filepath.Join("agents", numStr),
			filepath.Join("/app/agents", numStr),
		)
	}

	for _, candidate := range candidates {
		data, err := os.ReadFile(candidate)
		if err == nil {
			return strings.TrimSpace(string(data)), nil
		}
		if !errors.Is(err, os.ErrNotExist) {
			return "", fmt.Errorf("read AGENTS file %s: %w", candidate, err)
		}
	}

	return "", fmt.Errorf("agents file not found for project %d (%s)", projectID, projectName)
}

func convertEngineEvalToLLMEval(result *engine.EvalResult) *llm.Evaluation {
	if result == nil {
		return nil
	}

	issues := make([]llm.Issue, 0, len(result.Suggestions))
	for _, suggestion := range result.Suggestions {
		suggestion = strings.TrimSpace(suggestion)
		if suggestion == "" {
			continue
		}
		issues = append(issues, llm.Issue{
			Severity:    "medium",
			Description: suggestion,
			Suggestion:  suggestion,
		})
	}

	verdict := strings.ToLower(strings.TrimSpace(result.Verdict))
	evaluation := &llm.Evaluation{
		Verdict:      mapEngineVerdict(verdict),
		Confidence:   result.Confidence,
		Completeness: result.Confidence,
		Correctness:  result.Confidence,
		Conventions:  result.Confidence,
		ScopeOK:      verdict != "retry",
		Issues:       issues,
		Summary:      strings.TrimSpace(result.Analysis),
	}

	switch verdict {
	case "pass":
		evaluation.ScopeOK = true
		if evaluation.Correctness < 0.7 {
			evaluation.Correctness = 0.7
		}
	case "retry":
		evaluation.ScopeOK = false
		if evaluation.Correctness > 0.4 {
			evaluation.Correctness = 0.4
		}
	case "escalate":
		evaluation.ScopeOK = true
		if evaluation.Correctness < 0.6 {
			evaluation.Correctness = 0.6
		}
	}

	return evaluation
}

func mapEngineVerdict(verdict string) string {
	switch verdict {
	case "pass":
		return "accept"
	case "retry":
		return "iterate"
	default:
		return "escalate"
	}
}

func resolveRepoPathForEval(projectName string, session launcher.Session, workDir string) string {
	candidates := make([]string, 0, 4)
	if projectName != "" {
		candidates = append(candidates, resolveRepoPath(projectName))
	}
	if session.ProjectID > 0 {
		candidates = append(candidates, resolveRepoPath(strconv.FormatInt(session.ProjectID, 10)))
	}
	if strings.TrimSpace(workDir) != "" {
		candidates = append(candidates, strings.TrimSpace(workDir))
	}

	for _, candidate := range candidates {
		candidate = strings.TrimSpace(candidate)
		if candidate == "" {
			continue
		}
		info, err := os.Stat(candidate)
		if err == nil && info.IsDir() {
			return candidate
		}
	}

	return ""
}

func resolveRepoPath(projectRef string) string {
	projectRef = strings.TrimSpace(projectRef)
	if projectRef == "" {
		return ""
	}

	candidates := []string{projectRef}
	if filepath.IsAbs(projectRef) {
		candidates = append(candidates, projectRef)
	}

	if cwd, err := os.Getwd(); err == nil && strings.EqualFold(filepath.Base(cwd), projectRef) {
		candidates = append(candidates, cwd)
	}

	if reposDir := configuredReposDir(); reposDir != "" {
		candidates = append(candidates,
			filepath.Join(reposDir, projectRef),
			filepath.Join(reposDir, strings.ToLower(projectRef)),
		)
	}

	for _, candidate := range candidates {
		info, err := os.Stat(candidate)
		if err == nil && info.IsDir() {
			return candidate
		}
	}

	return ""
}

func configuredReposDir() string {
	for _, envName := range []string{"HIVEMIND_REPOS_DIR", "CODEX_REPOS_DIR", "REPOS_DIR"} {
		if value := strings.TrimSpace(os.Getenv(envName)); value != "" {
			return value
		}
	}

	configPath := strings.TrimSpace(os.Getenv("CONFIG_PATH"))
	if configPath == "" {
		configPath = "config.yaml"
	}

	data, err := os.ReadFile(configPath)
	if err != nil {
		return ""
	}

	var cfg struct {
		Codex struct {
			ReposDir string `yaml:"repos_dir"`
		} `yaml:"codex"`
	}
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return ""
	}

	return strings.TrimSpace(cfg.Codex.ReposDir)
}

func launcherWorkDir(launcher evaluatorLauncher) string {
	if launcher == nil {
		return ""
	}
	return strings.TrimSpace(launcher.GetWorkDir())
}

func shellQuotePath(path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		return path
	}
	return "'" + strings.ReplaceAll(path, "'", `'"'"'`) + "'"
}

func decideAction(evaluation *llm.Evaluation, forceIterate bool, retryCount int) string {
	if evaluation == nil {
		if retryCount < 2 {
			return "iterate"
		}
		return "escalate"
	}

	verdict := strings.ToLower(strings.TrimSpace(evaluation.Verdict))
	if isAcceptVerdict(verdict) && evaluation.ScopeOK && evaluation.Correctness >= 0.6 && !forceIterate {
		return "accept"
	}

	iteratePreferred := forceIterate || isIterateVerdict(verdict) || !evaluation.ScopeOK || evaluation.Correctness < 0.6
	if iteratePreferred && retryCount < 2 {
		return "iterate"
	}

	return "escalate"
}

func isAcceptVerdict(verdict string) bool {
	switch verdict {
	case "accept", "accepted", "approved", "pass", "passed", "ok":
		return true
	default:
		return false
	}
}

func isIterateVerdict(verdict string) bool {
	switch verdict {
	case "iterate", "retry", "changes_requested", "rework", "revise", "fix":
		return true
	default:
		return false
	}
}

func retryBranchName(base string, retry int) string {
	clean := strings.TrimSpace(base)
	if clean == "" {
		clean = fmt.Sprintf("retry-%d", time.Now().Unix())
	}
	return fmt.Sprintf("%s-r%d", clean, retry)
}

func buildIterationCache(session launcher.Session, evaluation *llm.Evaluation, retry int) string {
	issues := make([]string, 0)
	if evaluation != nil {
		for _, issue := range evaluation.Issues {
			issues = append(issues, fmt.Sprintf("[%s] %s -> %s", issue.Severity, issue.Description, issue.Suggestion))
		}
	}

	return strings.TrimSpace(fmt.Sprintf(
		"Reintento #%d solicitado por evaluator para session %s.\nResumen: %s\nIssues:\n- %s",
		retry,
		session.SessionID,
		safeEvalSummary(evaluation),
		strings.Join(issues, "\n- "),
	))
}

func safeEvalSummary(evaluation *llm.Evaluation) string {
	if evaluation == nil {
		return "sin evaluacion"
	}
	if strings.TrimSpace(evaluation.Summary) != "" {
		return strings.TrimSpace(evaluation.Summary)
	}
	return strings.TrimSpace(evaluation.Verdict)
}

func firstAvailableConsultant(consultants []llm.ConsultantClient) llm.ConsultantClient {
	for _, consultant := range consultants {
		if consultant != nil && consultant.IsAvailable() {
			return consultant
		}
	}
	return nil
}

func (e *Evaluator) escalateToUser(ctx context.Context, projectID int64, taskID int64, workerID *int64, reason string) error {
	e.mu.Lock()
	evalNotifier := e.notifier
	e.mu.Unlock()

	if e.db == nil {
		if evalNotifier != nil {
			projectRef := strconv.FormatInt(projectID, 10)
			if projectID <= 0 {
				projectRef = "unknown"
			}
			approvalID := fmt.Sprintf("input-%d-%d", projectID, taskID)
			_ = evalNotifier.NotifyNeedsInput(ctx, projectRef, strings.TrimSpace(reason), approvalID)
		}
		return nil
	}

	status := state.TaskStatusBlocked
	if taskID > 0 {
		if err := e.db.UpdateTask(ctx, taskID, state.TaskUpdate{Status: &status}); err != nil {
			return fmt.Errorf("mark task %d blocked: %w", taskID, err)
		}
	}

	if projectID > 0 {
		projectStatus := state.ProjectStatusNeedsInput
		if err := e.db.UpdateProjectStatus(ctx, projectID, projectStatus); err != nil && !errors.Is(err, state.ErrNotFound) {
			return fmt.Errorf("mark project %d needs_input: %w", projectID, err)
		}
	}

	if projectID > 0 {
		description := fmt.Sprintf("Evaluator escalated task %d for user input: %s", taskID, strings.TrimSpace(reason))
		if err := e.db.AppendEvent(ctx, state.Event{
			ProjectID:   projectID,
			WorkerID:    workerID,
			EventType:   "input_needed",
			Description: description,
		}); err != nil {
			return fmt.Errorf("append escalation event for project %d: %w", projectID, err)
		}
	}

	if evalNotifier != nil {
		projectRef := strconv.FormatInt(projectID, 10)
		if projectID > 0 {
			if project, err := e.db.GetProjectByID(ctx, projectID); err == nil && strings.TrimSpace(project.Name) != "" {
				projectRef = strings.TrimSpace(project.Name)
			}
		}
		approvalID := fmt.Sprintf("input-%d-%d", projectID, taskID)
		_ = evalNotifier.NotifyNeedsInput(ctx, projectRef, strings.TrimSpace(reason), approvalID)
	}

	return nil
}

func optionalWorkerID(workerID int64) *int64 {
	if workerID <= 0 {
		return nil
	}
	ref := workerID
	return &ref
}

func escalationReason(evaluation *llm.Evaluation) string {
	if evaluation == nil {
		return "manual review required"
	}

	parts := make([]string, 0, 3)
	if verdict := strings.TrimSpace(evaluation.Verdict); verdict != "" {
		parts = append(parts, "verdict="+verdict)
	}
	if summary := strings.TrimSpace(evaluation.Summary); summary != "" {
		parts = append(parts, summary)
	}
	if len(evaluation.Issues) > 0 {
		parts = append(parts, fmt.Sprintf("%d issue(s) detected", len(evaluation.Issues)))
	}
	if len(parts) == 0 {
		return "manual review required"
	}

	return strings.Join(parts, "; ")
}

func (e *Evaluator) getRetryCount(taskID int64) int {
	e.mu.Lock()
	defer e.mu.Unlock()
	return e.retries[taskID]
}

func (e *Evaluator) setRetryCount(taskID int64, retry int) {
	e.mu.Lock()
	defer e.mu.Unlock()
	e.retries[taskID] = retry
}
